### ISSUE TITLE
Add information and directions to readme

### ISSUE THREAD

**Issue by joegesualdo** [execonline-inc/aws-lambda-boilerplate#1]
It would be helpful to have some information in the readme. Some ideas:

- Information about what this is
- How to get started directions

**Comment by costajohnt** [comment]
how is it looking now?

**Comment by ilyakatz** [comment]
there is a comment in the readme

> serverless create --template aws-nodejs

why do you need to run this? the point of this starter project is to create a aws lambda boilerplate that fits us, instead of the generic severless boilerplate
